### ISSUE TITLE
Using this today

### ISSUE THREAD

**Issue by krum110487** [SciresM/3DS-SSL-Patch#3]
Hello,

I am very very new to 3Ds modding, and I have a need to see urls from a game, I have a few questions.

1) does this still work with modern luma, I saw you have to modify it slightly, but I don't want to brick my 3DS
2) do you happen to have this installed already? I need one Games urls checked so I can backup and preserve the games made and shared in "rpg maker fes" I really want to back up the games and I suspect it is probably a simple https request to download from their servers. They have a free fes player, I would love just to have a few logs of games downloading so I could investigate scraping it.

If it is not something you're interested in, or something you don't have time for, I 100% understand, I'm just apprehensive to install this because I have no idea what I'm doing when it comes to modding the 3DS.

**Comment by SciresM** [comment]
Hello,

1) I have no idea, sorry. I haven't touched this (or the 3DS, really) in literally years.

2) No, I haven't touched my 3DS since 2017/2018.

**Comment by krum110487** [comment]
No problem! Thanks for getting back to me and letting me know.

**Comment by piratesephiroth** [comment]
I'm not sure if it still works either but you don't need to install anything on the 3DS
